### ISSUE TITLE
Confirm all 10-pin modules work

### ISSUE THREAD

**Issue by Frijol** [tessel/hardware-modules#7]
Make sure all of Tessel's modules are fully functional on Tessel 2

Absolutely must work:
- [x] Accelerometer
- [x] Ambient
- [x] Climate
- [x] GPS
- [x] Infrared
- [x] Relay
- [x] RFID
- [x] Servo

Not urgent; getting replaced by a USB module:
- [ ] Bluetooth Low Energy
- [ ] GPRS
- [ ] MicroSD

I believe @linusU is working on this – can you confirm?

**Comment by LinusU** [comment]
This is on my todo list :+1:

**Comment by LinusU** [comment]
| Module | Status | Last checked |
| --- | --- | --- |
| Climate | Works | 2015-07-23 |
| Ambient | ~~tessel/t2-firmware#74~~ <br>~~tessel/t2-firmware#78~~ <br>tessel/t2-firmware#112 | 2015-10-18 |
| RFID | ~~tessel/t2-firmware#75~~ <br> ~~tessel/t2-firmware#79~~ <br> ~~tessel/t2-firmware#76~~ <br> ~~tessel/t2-firmware/issues/108~~ <br> https://github.com/tessel/t2-firmware/issues/111 | 2015-09-02 |
| Accelerometer | ~~tessel/t2-firmware#76~~ <br> Works | 2015-09-02 |
| GPS | ~~tessel/t2-firmware#77~~ <br> tessel/gps-a2235h#19 | 2015-09-02 |
| Infrared | tessel/t2-firmware#112 | 2015-10-18 |
| Servo | Works | 2015-09-02 |
| Relay | ~~tessel/relay-mono#6~~ <br> Works | 2015-09-02 |

**Comment by johnnyman727** [comment]
@LinusU thanks for this useful table!

**Comment by LinusU** [comment]
5 working, 3 broken as of now.

I managed to test the relay manually but it should be noted that the tests currently dosen't work; hence the linked bug.

**Comment by Frijol** [comment]
Thanks for the update on this!

**Comment by Frijol** [comment]
Are you sure IR works? I'm getting:

``` sh
➜  ir  t2 run ir.js
INFO Looking for your Tessel...
INFO Connected to Tessel-02A337692559 over LAN
INFO Writing ir.js to RAM on Tessel-02A337692559 (299.008 kB)...
INFO Deployed.
INFO Running ir.js...
Could not retrieve firmware version and module ID. Attempting update.
Uploading new firmware...
timers.js:371
      immediate._onImmediate();
                ^
TypeError: immediate._onImmediate is not a function
    at processImmediate [as _immediateCallback] (timers.js:371:17)
INFO Stopping script...
```

**Comment by Frijol** [comment]
Relay is not working for me, either:

``` sh
➜  relay  t2 run relay.js
INFO Looking for your Tessel...
INFO Connected to Harold over LAN
INFO Writing relay.js to RAM on Harold (34.304 kB)...
INFO Deployed.
INFO Running relay.js...
Ready! Toggling relays...
pin.rawRead is async, pass in a callback to get the value
pin.rawRead is async, pass in a callback to get the value
/usr/lib/node/tessel-export.js:416
      cb(err, data === REPLY.HIGH ? 1 : 0);
      ^
TypeError: cb is not a function
    at _port.replyQueue.push.callback (/usr/lib/node/tessel-export.js:416:7)
    at null.<anonymous> (/usr/lib/node/tessel-export.js:159:29)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:402:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:520:20)
INFO Stopping script...
```

(I'm running through the start experience examples)

**Comment by LinusU** [comment]
@Frijol Could you try rebooting your t2 before testing the ir module. If I remember correctly I sometimes got that error but rebooting it usually solved it. It's being tracked here: tessel/t2-firmware#78

Regarding relay, it seems like there is a callback missing somewhere. I ran the code in `test/`; which code are you running?

**Comment by Frijol** [comment]
I was working from http://tessel.github.io/t2-start/modules/relay.html

Will try the reboot thing

**Comment by Frijol** [comment]
Still having the same issue with IR. It's possible that the Attiny on my IR actually does have old firmware, & I'm hitting a firmware update edge case..

**Comment by LinusU** [comment]
Hmm, yes, that could be it. We would need to fix that thought...

**Comment by adkron** [comment]
I'm getting the following when trying to run ambient:

``` bash
Could not retrieve firmware version and module ID. Attempting update.
Uploading new firmware...
/usr/lib/node/tessel-export.js:387
    throw new RangeError('Buffer size must be within 1-255');
    ^

RangeError: Buffer size must be within 1-255
    at Tessel.Port._txrx (/usr/lib/node/tessel-export.js:387:11)
    at Tessel.SPI.transfer (/usr/lib/node/tessel-export.js:734:14)
    at ISP._transfer (/tmp/remote-script/node_modules/ambient-attx4/node_modules/attiny-common/node_modules/avr-isp/index.js:540:12)
    at ISP._flashAll (/tmp/remote-script/node_modules/ambient-attx4/node_modules/attiny-common/node_modules/avr-isp/index.js:275:10)
    at /tmp/remote-script/node_modules/ambient-attx4/node_modules/attiny-common/node_modules/avr-isp/index.js:263:18
    at null.<anonymous> (/tmp/remote-script/node_modules/ambient-attx4/node_modules/attiny-common/node_modules/avr-isp/index.js:371:9)
    at null.<anonymous> (/usr/lib/node/tessel-export.js:207:31)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
```

**Comment by adkron** [comment]
GPS module feedback

``` bash
INFO Looking for your Tessel...
INFO Connected to Tessel-02A3D73CC63E over LAN
INFO Writing index.js to RAM on Tessel-02A3D73CC63E (44.032 kB)...
INFO Deployed.
INFO Running index.js...
/tmp/remote-script/node_modules/gps-a2235h/index.js:10
var hw = process.binding('hw');
                 ^

Error: No such module: hw
    at Error (native)
    at Object.<anonymous> (/tmp/remote-script/node_modules/gps-a2235h/index.js:10:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/index.js:11:14)
    at Module._compile (module.js:435:26)
```

I'm not sure what that should change to or if this needs a complete reworking.

**Comment by LinusU** [comment]
@adkron Both of those issues are reported, it's the last issue listed in the table under ambient and gps in my first comment.

**Comment by adkron** [comment]
Thanks, @LinusU, I didn't even notice those were issue links. Maybe I should have tried them before jumping on everything.

**Comment by LinusU** [comment]
No problem :ok_hand: they are easy to miss
